name: strangefish
channels:
  - defaults
dependencies:
  - numpy>=1.16.4
  - pip>=19.2.2
  - python>=3.7.4
  - tqdm>=4.32.1
  - pip:
    - click>=7.0
    - python-chess>=0.28.2
    - pyyaml>=5.1.2
    - reconchess>=1.6.7
    - requests>=2.22.0
